# Generated by Django 5.2.1 on 2025-05-13 16:55

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=255)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('file', models.FileField(upload_to=main.models.BookCover.upload_to)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='main.book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('books', models.ManyToManyField(related_name='genres', to='main.book')),
            ],
        ),
    ]
