# Generated by Django 5.2.1 on 2025-05-15 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.PositiveIntegerField(choices=[('на рассмотрении', 1), ('отклонено', 2), ('одобрено', 3)], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.book'),
        ),
    ]
