# Generated by Django 5.2.1 on 2025-05-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_review_book'),
        ('main', '0006_review_status_alter_review_book'),
    ]

    operations = [
    ]
